### ISSUE TITLE
Query the uploaded videos for number of views and show them on "my uploaded videos"-tab

### ISSUE THREAD

**Issue by paltorg** [SYNQfm/SYNQ-WP#14]
Query the uploaded videos for number of views and show them on "my uploaded videos"-tab

**Comment by paltorg** [comment]
Maybe combined with https://github.com/SYNQfm/SYNQ-WP/issues/8

**Comment by batmany13** [comment]
Bumping up priority of this

**Comment by batmany13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WP plugin improvements](https://trello.com/c/N0gEe22p/42-wp-plugin-improvements)

**Comment by batmany13** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WP Plugin support "Views"](https://trello.com/c/o1UxICrq/59-wp-plugin-support-views)

**Comment by jettlin** [comment]
WP Plugin deployed with views
