### ISSUE TITLE
Nonsensical error message appears when entering an API key in the Settings tab. 

### ISSUE THREAD

**Issue by kasperniclas** [SYNQfm/SYNQ-WP#21]
(https://github.com/SYNQfm/SYNQ-WP/tree/refactor-plugin) 
When I add an API key in the settings tab and click the Save button, the desired outcome is achieved, BUT, an error message appears on the top of the screen, reading, "Please insert correct value for color code in primary and secondary color.". 

See video: 
https://player.synq.fm/embed/218bce7189544784b7c9cb89a1341a20

**Comment by paltorg** [comment]
Probably related to player apperance

**Comment by Sind** [comment]
done
