### ISSUE TITLE
All video thumbnails in the My Uploads tab link to the same video

### ISSUE THREAD

**Issue by kasperniclas** [SYNQfm/SYNQ-WP#22]
In the refactor version, all video thumbnails in the My Uploads tab link to the same video:
https://player.synq.fm/embed/c5dea67535b644fdab8c2990d4bd0e33

**Comment by paltorg** [comment]
So the shortcode link that is added in the posts/pages are correct, but when you click it before adding a video it all links to the same video.

**Comment by Sind** [comment]
done in refactor branch
