### ISSUE TITLE
Dynamically resize "my uploads" page

### ISSUE THREAD

**Issue by Sind** [SYNQfm/SYNQ-WP#28]
If the resolution of the computer/window is below a certain size, resize the cards for the uploaded videos so there will always be 3 cards minimum:

![image](https://user-images.githubusercontent.com/2745906/30654866-8a8fc0f0-9e2f-11e7-8d3d-d246c880b905.png)

**Comment by jettlin** [comment]
This should no longer need to be done as we switched to a table view with "vw" CSS
