### ISSUE TITLE
Excessive white space above SYNQ settings panel

### ISSUE THREAD

**Issue by kasperniclas** [SYNQfm/SYNQ-WP#3]
There is a lot of empty space above the SYNQ settings panel in the dashboard: 
<img width="812" alt="skjermbilde 2017-05-19 kl 13 33 07" src="https://cloud.githubusercontent.com/assets/12811284/26246168/0c7bed7c-3c98-11e7-9b05-2099c927c4e1.png">
The empty space above the tabs should not be there.

**Comment by halvardos** [comment]
This is caused by a div for error messages.
I think this should just be completely removed and we should add feedback messages later on.
Since that part is also completely lacking as far as I can tell.

**Comment by kasperniclas** [comment]
Looks like this can be closed now @halvardos ?

**Comment by Sind** [comment]
done in refactor branch
