### ISSUE TITLE
User Filter missing names

### ISSUE THREAD

**Issue by jettlin** [SYNQfm/SYNQ-WP#32]
User filter isn't showing all names.  Need to look into why...

**Comment by jettlin** [comment]
Cannot reproduce locally... May need to test on catchup ninja

**Comment by jettlin** [comment]
Found the issue:  when using `array_unique` its return items at the wrong indices.  Need to figure out how to map these correctly...

**Comment by jettlin** [comment]
Issue repaired, deploying fix to catchup.ninja

**Comment by gsemino** [comment]
This change looks good, closing issue.
