### ISSUE TITLE
Removing select all box

### ISSUE THREAD

**Issue by gsemino** [SYNQfm/SYNQ-WP#34]
At the moment select all box will select all videos but cannot be used to delete all videos, perhaps consider removing for now

**Comment by jettlin** [comment]
@gsemino Do we want to remove it for now or do we want to assume that the confirmation would be good enough?  Like if you select ALL the boxes its going to do the same functionality as if it was a single item...

**Comment by jettlin** [comment]
Changed delete behaviour to allow delete all and made delete button visible.

**Comment by gsemino** [comment]
Changes look good, it has confirmation for when deleting all so that should work fine and it grays out now when not active.
