### ISSUE TITLE
Font and color on the uploads tab

### ISSUE THREAD

**Issue by gsemino** [SYNQfm/SYNQ-WP#35]
Currently the font and color on the uploads tab is different from the other tabs, background is different as well. Standardize it to look like the other tabs.

**Comment by jettlin** [comment]
Background on API Key tab: rgb(249, 249, 249)
Background on Uploads tab (unless highlighted): rgb(249, 249, 249)

The backgrounds are exactly the same.  As for the font, it was requested to move towards System UI fonts by Kasper.  As such, we will move towards using System UI.  Color is the same across the board.  The greyed table headers is also per Kasper's request via the UI mockups.

**Comment by gsemino** [comment]
Josh and I decided text at top of the 'Uploaded' videos tab will look like the other tabs, if we want this changed in the future, a new ticket can be filed and scheduled.

**Comment by gsemino** [comment]
This change looks good, closing issue.
