### ISSUE TITLE
Videos uploaded to a project (api-key) are not displayed in 'My uploads'

### ISSUE THREAD

**Issue by kasperniclas** [SYNQfm/SYNQ-WP#4]
The plugin should fetch all videos associated with a project (API key) and show them in the 'My uploads' tab in the SYNQ settings panel in the dashboard. Now, if I have installed the plugin, added an API key and uploaded a video, that video will disappear if I delete the plugin - alse if I re-install and add the same API key.

The problem is possibly associated with the way we handle shortcodes, and that these are deleted when the plugin is deleted?

**Comment by halvardos** [comment]
The problem seems to be that instead of querying SYNQ for videos, video ids are stored in the local db. This table is then cleared if the plugin is removed.

This also means that any video uploaded from anywhere else will not be displayed.

**Comment by kasperniclas** [comment]
Not sure if it is viable but maybe we could store the shortcode for each video as a user data entry in each respective video object? Then the plugin could query for every video in a project containing some WP-plugin-specific phrase and list them in the My uploads interface. @halvardos

**Comment by halvardos** [comment]
Sure, that is viable. But why not get all videos that have finished transcoding and display them all?

**Comment by kasperniclas** [comment]
If the plugin is deleted, but some posts still have shortcodes in them, that link will be lost and the videos will be gone even if a user re-installs the plugin - unless the shortcode is stored within or otherwise associated with the video object, wouldn’t it?

**Comment by halvardos** [comment]
I think the shortcode should use the video_id. that way it would continue to work as soon as you installed the plugin again.

**Comment by kasperniclas** [comment]
Yes that might be the best way to solve it

**Comment by Sind** [comment]
done in refactor branch
