### ISSUE TITLE
Error from variable vast_tag when updating API key

### ISSUE THREAD

**Issue by paltorg** [SYNQfm/SYNQ-WP#5]
it's a minor error saying the variable vast_tag is missing probably it is the returned value in your api when activating the license

**Comment by kasperniclas** [comment]
@paltorg This doesn't apply to the latest version of the plugin (https://github.com/SYNQfm/SYNQ-WP/tree/refactor-plugin), close?

**Comment by Sind** [comment]
done in refactor branch
