### ISSUE TITLE
Add time/date stamp and tags on videos in "My uploads"-tab

### ISSUE THREAD

**Issue by paltorg** [SYNQfm/SYNQ-WP#8]
Add time/date stamp and tags on videos in "My uploads" and the possibility to sort and search

See attached mockup
![synq catchup ninja wordpress](https://user-images.githubusercontent.com/25321467/29208866-1a2780ea-7e8c-11e7-8b7e-fdb58c73d54e.png)

**Comment by Sind** [comment]
keep each issue separate please.
