### ISSUE TITLE
Add specification on supported file formats, qualities and resolution for logo on customization tab

### ISSUE THREAD

**Issue by paltorg** [SYNQfm/SYNQ-WP#9]
Add specification on supported file formats, qualities and resolution for logo on customization tab. Describe below upload box.

**Comment by paltorg** [comment]
Functionality will be removed when implementing https://github.com/SYNQfm/SYNQ-WP/issues/12 Could be added in a later version.

**Comment by jettlin** [comment]
Since this won't be fixed, closing ticket
